Key: 32C7D1D29800014-SM
GameFolder: C:\Games\World of Warcraft
AddonName: WeakAurasModule
Debug: false
DebugAura: false
DebugSpell: false
DebugPower: false
InputDelay: 25
IconOverlayEnabled: true
IconOverlayX: 1264
IconOverlayY: 842
IconOverlaySize: 40
shared_config:
  interrupt_pct: 20
  healthpotion: 40
  interrupt_all: true
  healthstone: 50
selected_rotation:
  104: C:\Games\Slack\FerrazGuardian.yaml